version: '3'
services:
  server:
    build:
      context: Container1
    ports:
      - "11211:11211"
    volumes:
      - key-share-volume:/home/ubuntu/.ssh/
  client:
    build:
      context: Container2
    ports:
      - "10022:2022"
    volumes:
      - key-share-volume:/home/ubuntu/share_pkey
    depends_on:
      - server
volumes:
  key-share-volume:
